### ISSUE TITLE
OpenBabel 3 support?

### ISSUE THREAD

**Issue by jotjot** [partridgejiang/cheminfo-to-web#4]
Is there a chance you might change the binding for the new OpenBabel::OBAtom? Many things have changed from 2.4.1 to 3.0.

**Comment by partridgejiang** [comment]
I'll inspect 3.0 later. By the way, is 3.0 officially published? I found it on the GitHub repo but not on the OpenBabel website (still 2.4.0 on it), :(.

**Comment by jotjot** [comment]
Version 3.0.0 was released on GitHub on Oktober 10 last year, just a few days ago version 3.1.1 was released. If you go to the OpenBabel website it does not mention v3 in the news, but when you go on downloads [http://openbabel.org/wiki/Category:Installation] it will direct you to the latest version, which now is 3.1.1. 
Thank you! I do not know enough about OpenBabel's internal structure to make the changes.

**Comment by partridgejiang** [comment]
@jotjot, build of OpenBabel3 was added now, please check OpenBabel3/OpenBabel-js/bin/ directory for the compilation. Enjoy, :).

**Comment by jotjot** [comment]
Thank you!!
