### ISSUE TITLE
Unable to get atom charge in Indigo JS bindings

### ISSUE THREAD

**Issue by baoilleach** [partridgejiang/cheminfo-to-web#6]
Hi @partridgejiang, thanks for all your work on this. I am using the Indigo bindings, and they are working really well and seem pretty fast.

I only have one problem, which you may know the answer to, or a solution for. Given an atom, I am unable to get the charge on it. This is because getCharge requires two parameters: the first is the handle to the atom, and the second is a pointer to an integer (to hold the return value). I've tried just passing in a JavaScript variable for the second parameter and that doesn't work. I was then thinking about using malloc to create a pointer and send it in. I think this might work, but I can't find the emscripten methods that would let me read that memory (getValue).

Have you come across this problem before? Any thoughts?

**Comment by partridgejiang** [comment]
Hi @baoilleach, the second *int parameter of C function can not be retrieved simply by a JavaScript number variable. Actually, in Emscripten, this type of C function is binded to JavaScript function with the following signature:
```js
getCharge(number, array);
```
Then the returned value can be filled in array and be read out. The following code should work (although not tested by myself yet):
```js
let a = [];
Indigo.getCharge(atomIndex, a);
let charge = a[0];
```
Please try it and let me know your result if possible, :).

**Comment by partridgejiang** [comment]
Hi @baoilleach, there used to be some incorrect parameter bindings in the exported JS functions. Just did some modification and please check the latest files in this repo. Now the getCharge can be called as the following:
```js
let Indigo = CreateIndigo(module);   // module is the Indigo wasm module object
let IndigoModule = Indigo._module;
// ...
let buf = IndigoModule._malloc(4);  // malloc buf for int
Indigo.getCharge(atom, buf);
let charge = IndigoModule.getValue(buf, 'i32');
```

**Comment by baoilleach** [comment]
If this works, that's awesome, but isn't it late at night there? Get some sleep :-) I'll tell you how it goes in the morning!

**Comment by baoilleach** [comment]
And it works! 
![image](https://user-images.githubusercontent.com/45337/213879111-d55370ed-6313-444c-810b-bdc17092a159.png)
